apiVersion: apps/v1
kind: Deployment
metadata:
  name: census-database
  namespace: census
spec:
  replicas: 1
  selector:
    matchLabels:
      app: census-database
  template:
    metadata:
      labels:
        app: census-database
    spec:
      containers:
      - name: census-database
        image: census-database:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "touch /data/census.sqlite && chmod 666 /data/census.sqlite && python -m scripts.database"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: census-data-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: census-transform
  namespace: census
spec:
  replicas: 1
  selector:
    matchLabels:
      app: census-transform
  template:
    metadata:
      labels:
        app: census-transform
    spec:
      containers:
      - name: census-transform
        image: census-transform:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: census-load
  namespace: census
spec:
  replicas: 1
  selector:
    matchLabels:
      app: census-load
  template:
    metadata:
      labels:
        app: census-load
    spec:
      containers:
      - name: census-load
        image: census-load:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: census-main
  namespace: census
spec:
  replicas: 1
  selector:
    matchLabels:
      app: census-main
  template:
    metadata:
      labels:
        app: census-main
    spec:
      containers:
      - name: census-main
        image: census-main:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: census-database
  namespace: census
spec:
  type: LoadBalancer
  selector:
    app: census-database
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: census-transform
  namespace: census
spec:
  type: LoadBalancer
  selector:
    app: census-transform
  ports:
  - port: 8001
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: census-load
  namespace: census
spec:
  type: LoadBalancer
  selector:
    app: census-load
  ports:
  - port: 8002
    targetPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: census-main
  namespace: census
spec:
  type: LoadBalancer
  selector:
    app: census-main
  ports:
  - port: 8003
    targetPort: 8003 