kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: etl-pipeline-cluster
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://localhost:5001"] 