apiVersion: v1
kind: PersistentVolume
metadata:
  name: census-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/census
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: census-data-pvc
  namespace: census
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 