apiVersion: batch/v1
kind: Job
metadata:
  name: database-init
  namespace: census
spec:
  template:
    spec:
      containers:
      - name: init
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          touch /data/census.sqlite
          chmod 666 /data/census.sqlite
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: census-pvc
      restartPolicy: Never
  backoffLimit: 4 