kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 5000
    hostPort: 5000
    protocol: TCP
  - containerPort: 8000
    hostPort: 8000
    protocol: TCP
  - containerPort: 8001
    hostPort: 8001
    protocol: TCP
  - containerPort: 8002
    hostPort: 8002
    protocol: TCP
  - containerPort: 8003
    hostPort: 8003
    protocol: TCP
- role: worker