apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      labels:
        app: load
    spec:
      containers:
      - name: load
        image: localhost:5001/etl-load:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_PATH
          value: /data/census.sqlite
        - name: RESULTS_DIR
          value: /results
        - name: TRANSFORMED_DATA_PATH
          value: /data/transformed_data.json
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data
          mountPath: /data
        - name: results
          mountPath: /results
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: etl-data-pvc
      - name: results
        persistentVolumeClaim:
          claimName: etl-data-pvc