apiVersion: v1
kind: Service
metadata:
  name: census-main-external
  namespace: census
  labels:
    app: census
    component: main
spec:
  type: NodePort
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30003
  selector:
    app: census
    component: main 