apiVersion: v1
kind: PersistentVolume
metadata:
  name: census-pv
  labels:
    type: local
spec:
  storageClassName: census-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/census"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - etl-pipeline-cluster-worker
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: census-results-pv
  labels:
    type: local
spec:
  storageClassName: census-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/results"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - etl-pipeline-cluster-worker
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain