apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: census-results-pvc
  namespace: census
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 