apiVersion: v1
kind: PersistentVolume
metadata:
  name: census-results-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /results
    type: DirectoryOrCreate 