apiVersion: apps/v1
kind: Deployment
metadata:
  name: census-transform
  namespace: census
  labels:
    app: census
    component: transform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: census
      component: transform
  template:
    metadata:
      labels:
        app: census
        component: transform
    spec:
      containers:
      - name: transform
        image: localhost:5000/census-transform:latest
        imagePullPolicy: Always
        env:
        - name: DB_PATH
          value: "/data/census.sqlite"
        - name: CSV_PATH
          value: "/data/input/census.csv"
        - name: TRANSFORMED_DATA_PATH
          value: "/data/transformed_data.json"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: scripts-volume
          mountPath: /app/scripts
        - name: census-data
          mountPath: /data/input
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: census-pvc
      - name: scripts-volume
        configMap:
          name: census-scripts
      - name: census-data
        configMap:
          name: census-data
      restartPolicy: Always