apiVersion: apps/v1
kind: Deployment
metadata:
  name: transform-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transform
  template:
    metadata:
      labels:
        app: transform
    spec:
      containers:
      - name: transform
        image: localhost:5001/etl-transform:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_PATH
          value: /data/census.sqlite
        - name: CSV_PATH
          value: /data/census.csv
        - name: TRANSFORMED_DATA_PATH
          value: /data/transformed_data.json
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: etl-data-pvc