name: CI-CD Pipeline for ETL Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Manual trigger via GitHub UI
    inputs:
      reason:
        description: 'Reason for manually triggering the workflow'
        required: true
        default: 'Manual run requested'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # Step 4: Run linting with flake8
      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=88 --extend-ignore=E203 --exit-zero

      # Step 5: Run tests with pytest
      - name: Run tests
        run: |
          pytest tests/ --verbose

      # Step 6: Run ETL pipeline
      - name: Run ETL pipeline
        run: |
          python main.py

      # Step 7: Upload artifacts (reports and visualizations)
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: etl-results
          path: results/
          retention-days: 7

      # Step 8: Log manual trigger reason (if applicable)
      - name: Log manual trigger reason
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Workflow manually triggered. Reason: ${{ github.event.inputs.reason }}"